version: '3.8'

services:
  dbank-assignment-mongodb:
    image: mongo:4.0
    command: mongod --port 5415 --auth
    container_name: "dbank-assignment-db"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=assignment-admin
      - MONGO_INITDB_ROOT_PASSWORD=uF*3lviO0iaZcKTT479_t
      - MONGO_INITDB_DATABASE=dbank-assignment
    ports:
      - 5415:5415
    networks:
      - assignment-db-dockernet
    volumes:
      - db-assignment-volume:/data/db
      - ./mongo-import.sh:/docker-entrypoint-initdb.d/mongo-import.sh
      - ./customers.json:/docker-entrypoint-initdb.d/customers.json
      - ./branches.json:/docker-entrypoint-initdb.d/branches.json
    healthcheck:
      test: mongosh --port 5415 --eval 'db.runCommand("ping").ok' --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  core:
    build:
      context: ./core
      dockerfile: Dockerfile
    container_name: core
    ports:
      - "8083:8083"
    depends_on:
      dbank-assignment-mongodb:
        condition: service_healthy
    networks:
      - assignment-db-dockernet
    volumes:
      - ./logs:/var/log
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  transaction-producer:
    build:
      context: ./transaction_producer
      dockerfile: Dockerfile
    container_name: transaction-producer
    ports:
      - "8080:8080"
      - "9091:9091"
    networks:
      - assignment-db-dockernet
    volumes:
      - ./logs:/var/log
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - GRPC_SERVER_PORT=9091
    depends_on:
      - core

  fraud-detector:
    build:
      context: ./fraud_detector
      dockerfile: Dockerfile
    container_name: fraud-detector
    ports:
      - "8081:8081"
    networks:
      - assignment-db-dockernet
    volumes:
      - ./logs:/var/log
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - core

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"
    networks:
      - assignment-db-dockernet

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - assignment-db-dockernet

volumes:
  db-assignment-volume:

networks:
  assignment-db-dockernet:
    driver: bridge 