global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'transaction-producer'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['transaction-producer:8080']
  
  - job_name: 'fraud-detector'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['fraud-detector:8081'] 