spring:
  application:
    name: fraud-detector
  data:
    mongodb:
      uri: mongodb://assignment-admin:uF*3lviO0iaZcKTT479_t@dbank-assignment-mongodb:5415/dbank-assignment?authSource=admin
      database: dbank-assignment
      auto-index-creation: true
  kafka:
    topics:
      transaction-events: transaction-events
    bootstrap-servers: kafka:29092
    consumer:
      group-id: fraud-detector-group
    listener:
      ack-mode: MANUAL_IMMEDIATE
      missing-topics-fatal: false
  config:
    activate:
      on-profile: docker
server:
  port: 8081

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  level:
    root: INFO
    com.furkanalniak.assignment: DEBUG
    org.apache.kafka: DEBUG
    org.springframework.kafka: DEBUG